"""
Django settings for DjangoProject project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from qdrant_client import QdrantClient

from assistant import Assistant

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gm$n(div8fexkfu0w6vekr_q9h&hh6mv6grcw_lf%o4*xa@&*-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0', 'localhost', '127.0.0.1', '*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'app.middleware.AccessMiddleware',
]

WHITENOISE_AUTOREFRESH = True
WHITENOISE_USE_FINDERS = True

ROOT_URLCONF = 'DjangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoProject.wsgi.application'
ASGI_APPLICATION = 'DjangoProject.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": os.getenv("DATABASE_HOST", "postgres"),
        "PORT": os.getenv("DATABASE_PORT", "5432"),
        "NAME": os.getenv("DATABASE_NAME", "chat_db"),
        "USER": os.getenv("DATABASE_USER", "chat_user"),
        "PASSWORD": os.getenv("DATABASE_PASSWORD", "strong_psw"),
        "CONN_MAX_AGE": 60,
        "OPTIONS": {
            "client_encoding": "UTF8"
        },
        "TEST": {
            "NAME": os.getenv("DATABASE_TEST_NAME", None),
        },
    }
}

if os.getenv("TEST_USE_SQLITE") == "1":
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Базовые настройки авторизации
LOGIN_URL = '/login/'  # Общий URL для перенаправления неавторизованных пользователей

OPERATOR_LOGIN_URL = '/login/operator/'  # URL для входа операторов
ADMIN_LOGIN_URL = '/login/admin/'  # URL для входа администраторов

# Перенаправления после успешного входа
OPERATOR_REDIRECT_URL = '/operator/'  # Куда идет оператор после входа
ADMIN_REDIRECT_URL = '/admin/'  # Куда идет админ после входа (будет создан позже)

# Глобальный выход
LOGOUT_REDIRECT_URL = '/login/'  # URL для перенаправления после выхода из системы

QDRANT_HOST = os.getenv("QDRANT_HOST", "qdrant")
QDRANT_PORT = os.getenv("QDRANT_PORT", "6333")
QDRANT_URL = os.getenv("QDRANT_URL", f"http://{QDRANT_HOST}:{QDRANT_PORT}")
QDRANT_IN_MEMORY = os.getenv("QDRANT_IN_MEMORY") == "1"

QDRANT = QdrantClient(":memory:") if QDRANT_IN_MEMORY else QdrantClient(url=QDRANT_URL)
COLLECTION = os.getenv("QDRANT_COLLECTION", "que")

USE_FAKE_ASSISTANT = os.getenv("USE_FAKE_ASSISTANT") == "1"

class DummyAssistant:
    async def __call__(self, message, max_related=5):
        return Assistant.Response(answer=f"stub: {message}", related_questions=[])

    async def answers(self, message):
        return []

    async def get_embedding(self, message):
        return [0.0, 0.0, 0.0]


assistant = DummyAssistant() if USE_FAKE_ASSISTANT else Assistant()
